import { trpc } from "@/lib/trpc";
import { ArrowLeft, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Expand, MapPin, MessageCircle, ShieldCheck, X } from "lucide-react";
import { useState } from "react";
import { useRoute } from "wouter";

export default function PublicProperty() {
  const token = new URLSearchParams(window.location.search).get("link") || "";
  const [, codeParams] = useRoute("/imovel/:code");
  const [, brokerParams] = useRoute("/corretor/:brokerSlug/imovel/:code");
  const [, brokerFemaleParams] = useRoute("/corretora/:brokerSlug/imovel/:code");
  const code = codeParams?.code || brokerParams?.code || brokerFemaleParams?.code || "";
  const brokerSlug = brokerParams?.brokerSlug || brokerFemaleParams?.brokerSlug || "";
  const signedFriendlyQuery = trpc.catalog.publicFriendlyLink.useQuery({ code, brokerSlug }, { enabled: !token && Boolean(code && brokerSlug), retry: false });
  const unsignedQuery = trpc.catalog.publicByCode.useQuery({ code }, { enabled: !token && Boolean(code && !brokerSlug), retry: false });
  const propertyQuery = trpc.catalog.publicLink.useQuery({ token }, { enabled: token.length > 0, retry: false });
  const activeQuery = token ? propertyQuery : (brokerSlug ? signedFriendlyQuery : unsignedQuery);
  const [photoIndex, setPhotoIndex] = useState(0);
  const [lightbox, setLightbox] = useState(false);

  if (!token && !code) return <EmptyState title="Link de imóvel inválido" text="Solicite um novo link público do imóvel." />;
  if (activeQuery.isLoading) return <div className="grid min-h-screen place-items-center bg-[#f4f6f7] text-sm text-slate-500">Preparando sua visita...</div>;
  if (activeQuery.error || !activeQuery.data) return <EmptyState title="Link de imóvel indisponível" text="O imóvel pode ter sido arquivado ou o link não é mais válido." />;

  const { property, broker, organization } = activeQuery.data;
  const photos = property.photos || [];
  const currentPhoto = photos[photoIndex];
  const whatsapp = broker?.phone ? `https://wa.me/${broker.phone}?text=${encodeURIComponent(`Olá ${broker.name.split(/\s+/)[0]}, vi a página do imóvel "${property.title}" (${property.price || "valor sob consulta"}) e gostaria de mais informações e de agendar uma visita.`)}` : "";
  const region = property.address?.match(/Capão da Canoa|Xangri-Lá|Maquiné|Parobé|Osório|Tramandaí|Torres|Carlos Barbosa|Porto Belo/i)?.[0];
  const bedrooms = property.bedrooms != null ? String(property.bedrooms) : `${property.title} ${(property.details || []).join(" ")} ${property.notes || ""}`.match(/(\d+)\s*dorm/i)?.[1];
  const area = property.privateArea || `${property.title} ${(property.details || []).join(" ")} ${property.notes || ""}`.match(/([\d.,]+)\s*m²/i)?.[1];
  const mapLink = property.mapUrl || (property.address ? `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(property.address)}` : "");

  return <main className="min-h-screen bg-[#f4f6f7] text-[#102c3d]">
    <div className="h-1.5 bg-gradient-to-r from-[#102c3d] via-[#d7b874] to-[#20bd63]" />
    <div className="mx-auto max-w-7xl px-4 py-5 sm:px-6 sm:py-8 lg:px-10 lg:py-10">
      <header className="mb-6 flex flex-col gap-4 rounded-[2rem] bg-white px-5 py-5 shadow-sm sm:flex-row sm:items-center sm:px-8 sm:py-6"><div className="grid h-28 w-28 shrink-0 place-items-center overflow-hidden rounded-[1.5rem] border border-slate-100 bg-white p-3 shadow-md sm:h-40 sm:w-40 sm:rounded-[1.8rem] sm:p-5">{organization?.logoUrl ? <img src={organization.logoUrl} alt={`Logo ${organization.name}`} className="h-full w-full object-contain" /> : <span className="text-3xl font-bold text-[#102c3d]">M</span>}</div><div className="min-w-0"><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-[#b38b3d]">Tabela de Imóveis</p><h1 className="mt-1 break-words text-2xl font-semibold tracking-tight text-[#102c3d] sm:text-4xl">{organization?.name || "MeuLink"}</h1><div className="mt-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-[#8e6d31]"><span className="h-2 w-2 rounded-full bg-[#20bd63]" /> Imóvel selecionado <span className="ml-1 rounded-full bg-[#f5f7f8] px-3 py-1.5 text-[10px] tracking-[0.12em]">{property.code}</span></div></div></header>

      <section className="relative min-h-[420px] overflow-hidden rounded-[2rem] bg-[#102c3d] shadow-[0_24px_70px_rgba(16,44,61,0.2)] sm:min-h-[520px]">
        {currentPhoto && <img src={currentPhoto} alt={`Capa de ${property.title}`} className="absolute inset-0 h-full w-full object-cover" />}
        <div className="absolute inset-0 bg-gradient-to-t from-[#06141d]/90 via-[#102c3d]/35 to-[#102c3d]/10" />
        <div className="relative z-10 flex min-h-[420px] flex-col justify-end p-6 text-white sm:min-h-[520px] sm:p-10 lg:p-14"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#f0d99e]">Imóvel disponível</p><h2 className="mt-3 max-w-4xl text-3xl font-semibold leading-[1.08] tracking-tight sm:text-5xl lg:text-6xl">{property.title}</h2><p className="mt-5 flex max-w-3xl items-start gap-2 text-sm leading-relaxed text-white/85 sm:text-base"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-[#f0d99e]" />{property.address || "Endereço sob consulta"}</p></div>
      </section>

      <section className="mt-5 overflow-hidden rounded-[2rem] bg-white p-3 shadow-sm sm:p-5"><div className="mb-3 flex items-center justify-between gap-3 px-1"><h2 className="text-base font-semibold text-[#102c3d] sm:text-lg">Galeria de imagens</h2>{photos.length > 0 && <span className="text-xs font-medium text-slate-500">{photoIndex + 1} de {photos.length}</span>}</div><div className="relative aspect-[4/3] min-h-[280px] w-full overflow-hidden rounded-[1.4rem] bg-[#e8edef] sm:aspect-[16/10] sm:min-h-0">{currentPhoto ? <img src={currentPhoto} alt={`Foto ${photoIndex + 1} de ${property.title}`} className="h-full w-full object-contain" /> : <div className="grid h-full place-items-center text-sm text-slate-500">Sem foto disponível</div>}{photos.length > 1 && <><button type="button" aria-label="Foto anterior" onClick={() => setPhotoIndex((photoIndex - 1 + photos.length) % photos.length)} className="absolute left-3 top-1/2 grid h-11 w-11 -translate-y-1/2 place-items-center rounded-full bg-[#102c3d]/80 text-white shadow-lg"><ChevronLeft className="h-5 w-5" /></button><button type="button" aria-label="Próxima foto" onClick={() => setPhotoIndex((photoIndex + 1) % photos.length)} className="absolute right-3 top-1/2 grid h-11 w-11 -translate-y-1/2 place-items-center rounded-full bg-[#102c3d]/80 text-white shadow-lg"><ChevronRight className="h-5 w-5" /></button></>}<button type="button" aria-label="Ampliar foto" onClick={() => setLightbox(true)} className="absolute bottom-3 right-3 inline-flex items-center gap-2 rounded-full bg-white/95 px-3 py-2 text-[11px] font-bold text-[#102c3d] shadow-lg"><Expand className="h-3.5 w-3.5" /> Ampliar</button></div>{photos.length > 1 && <div className="mt-3 flex gap-3 overflow-x-auto pb-1"><button type="button" onClick={() => setPhotoIndex(0)} className={`h-24 w-36 shrink-0 overflow-hidden rounded-xl border-2 transition sm:h-16 sm:w-24 ${photoIndex === 0 ? "border-[#d7b874] ring-2 ring-[#d7b874]/40" : "border-transparent opacity-65"}`}><img src={photos[0]} alt="Miniatura da capa" className="h-full w-full object-cover" /></button>{photos.slice(1).map((photo, offset) => { const index = offset + 1; return <button type="button" key={photo} onClick={() => setPhotoIndex(index)} className={`h-24 w-36 shrink-0 overflow-hidden rounded-xl border-2 transition sm:h-16 sm:w-24 ${index === photoIndex ? "border-[#d7b874] ring-2 ring-[#d7b874]/40" : "border-transparent opacity-65"}`}><img src={photo} alt={`Miniatura ${index + 1}`} className="h-full w-full object-cover" /></button>; })}</div>}</section>

      <div className="relative z-10 -mt-5 px-3 sm:px-8"><section className="grid gap-3 rounded-2xl bg-white p-4 shadow-xl sm:grid-cols-3 sm:p-5"><QuickFact value={bedrooms || "—"} label="Dormitórios" /><QuickFact value={area ? (area.includes("m²") ? area : `${area} m²`) : "—"} label="Área privativa" /><QuickFact value={region || "Consultar"} label="Localização" /></section></div>
      {mapLink && <div className="mt-4 flex justify-center"><a href={mapLink} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-[#d7b874] bg-white px-5 text-sm font-bold text-[#102c3d] shadow-sm transition hover:bg-[#fdfaf4]"><MapPin className="h-4 w-4 text-[#b38b3d]" /> Abrir localização no mapa</a></div>}

      <div className="mt-7 grid gap-5 lg:grid-cols-[1.35fr_.65fr]">
        <div className="space-y-5">{property.developmentInfo && <section className="rounded-3xl bg-white p-6 shadow-sm sm:p-8"><SectionHeading title="Sobre o empreendimento" /><p className="whitespace-pre-line text-sm leading-7 text-slate-600 sm:text-[15px]">{property.developmentInfo}</p></section>}{property.notes && <section className="rounded-3xl bg-white p-6 shadow-sm sm:p-8"><SectionHeading title="Sobre o imóvel" /><p className="whitespace-pre-line text-sm leading-7 text-slate-600 sm:text-[15px]">{property.notes}</p></section>}{property.details.length > 0 && <section className="rounded-3xl bg-white p-6 shadow-sm sm:p-8"><SectionHeading title="Características" /><div className="grid gap-2 sm:grid-cols-2">{property.details.map(detail => <div key={detail} className="flex items-center gap-2 rounded-xl border border-slate-100 bg-[#f8fafb] px-3 py-3 text-sm text-slate-600"><CheckCircle2 className="h-4 w-4 shrink-0 text-[#20bd63]" />{detail}</div>)}</div></section>}</div>
        <aside className="h-fit rounded-3xl bg-white p-6 shadow-sm sm:p-8 lg:sticky lg:top-6"><SectionHeading title={broker ? "Atendimento personalizado" : "Informações públicas"} />{broker && <div className="flex items-center gap-4"><div className="grid h-20 w-20 shrink-0 place-items-center overflow-hidden rounded-2xl border-4 border-[#d7b874] bg-[#102c3d] text-xl font-extrabold text-white">{broker.photoUrl ? <img src={broker.photoUrl} alt={`Foto de ${broker.name}`} className="h-full w-full object-cover" /> : broker.name.split(/\s+/).slice(0, 2).map(part => part[0]).join("").toUpperCase()}</div><div><p className="text-lg font-bold text-[#102c3d]">{broker.name}</p><p className="mt-1 text-xs text-slate-500">Consultoria particular e exclusiva</p><p className="mt-1 text-xs text-slate-500">Atendimento direto pelo WhatsApp</p></div></div>}{broker && <div className="mt-6 rounded-2xl border border-emerald-100 bg-emerald-50/70 p-4 text-xs leading-relaxed text-slate-600"><ShieldCheck className="mr-1 inline h-4 w-4 text-[#20bd63]" /><strong className="text-slate-700">Fale diretamente com seu consultor.</strong><br />Confirme disponibilidade, condições e agende uma visita.</div>}{broker && whatsapp && <a href={whatsapp} target="_blank" rel="noreferrer" className="mt-4 flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#20bd63] px-5 text-sm font-extrabold text-white transition hover:bg-[#12934a]"><MessageCircle className="h-5 w-5" /> WhatsApp do corretor</a>}{broker && <button type="button" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} className="mt-3 flex w-full items-center justify-center gap-2 text-xs font-semibold text-slate-500 hover:text-[#102c3d]"><CalendarDays className="h-4 w-4" /> Agende uma visita</button>}</aside>
      </div>
      <footer className="py-8 text-center text-[11px] text-slate-400">Valores e disponibilidade sujeitos a confirmação · {organization?.name || "MeuLink"}</footer>
    </div>
    {lightbox && currentPhoto && <div className="fixed inset-0 z-50 grid place-items-center bg-[#06141d]/95 p-4 sm:p-8" role="dialog" aria-modal="true"><button type="button" aria-label="Fechar galeria" onClick={() => setLightbox(false)} className="absolute right-5 top-5 rounded-full border border-white/20 bg-white/10 p-2 text-white"><X className="h-5 w-5" /></button><img src={currentPhoto} alt={`Foto ${photoIndex + 1}`} className="max-h-[86vh] max-w-[94vw] object-contain" />{photos.length > 1 && <div className="absolute bottom-7 flex gap-3"><button type="button" aria-label="Foto anterior" onClick={() => setPhotoIndex((photoIndex - 1 + photos.length) % photos.length)} className="rounded-xl bg-white/10 p-3 text-white"><ChevronLeft /></button><button type="button" aria-label="Próxima foto" onClick={() => setPhotoIndex((photoIndex + 1) % photos.length)} className="rounded-xl bg-white/10 p-3 text-white"><ChevronRight /></button></div>}</div>}
  </main>;
}

function SectionHeading({ title }: { title: string }) { return <h2 className="mb-5 border-l-4 border-[#d7b874] pl-3 text-xl font-semibold text-[#102c3d]">{title}</h2>; }
function QuickFact({ value, label }: { value: string; label: string }) { return <div className="rounded-xl bg-[#f8fafb] p-3 text-center"><strong className="block truncate text-sm font-bold text-[#102c3d]">{value}</strong><span className="mt-1 block text-[10px] font-medium uppercase tracking-[0.12em] text-slate-500">{label}</span></div>; }
function EmptyState({ title, text }: { title: string; text: string }) { return <main className="grid min-h-screen place-items-center bg-[#f4f6f7] p-6"><div className="w-full max-w-md rounded-3xl bg-white p-10 text-center shadow-xl"><ArrowLeft className="mx-auto mb-5 h-8 w-8 text-[#c7a15a]" /><h1 className="text-xl font-semibold text-[#102c3d]">{title}</h1><p className="mt-2 text-sm text-slate-500">{text}</p></div></main>; }
