import { trpc } from "@/lib/trpc";
import { ArrowLeft, ChevronLeft, ChevronRight, MapPin, MessageCircle, ShieldCheck, X } from "lucide-react";
import { useState } from "react";

export default function PublicProperty() {
  const token = new URLSearchParams(window.location.search).get("link") || "";
  const propertyQuery = trpc.catalog.publicLink.useQuery({ token }, { enabled: token.length > 0, retry: false });
  const [photoIndex, setPhotoIndex] = useState(0);
  const [lightbox, setLightbox] = useState(false);

  if (!token) return <EmptyState title="Link de imóvel inválido ou expirado" text="Solicite ao seu consultor um novo link de acesso." />;
  if (propertyQuery.isLoading) return <div className="grid min-h-screen place-items-center bg-[#fbfaf8] text-sm text-slate-500">Carregando imóvel...</div>;
  if (propertyQuery.error || !propertyQuery.data) return <EmptyState title="Link de imóvel inválido ou expirado" text="Solicite ao seu consultor um novo link de acesso." />;

  const { property, broker, organization } = propertyQuery.data;
  const photos = property.photos;
  const currentPhoto = photos[photoIndex];
  const whatsapp = `https://wa.me/${broker.phone}?text=${encodeURIComponent(`Olá ${broker.name.split(/\s+/)[0]}, vi a página do imóvel "${property.title}" (${property.price || "valor sob consulta"}) e gostaria de mais informações e de agendar uma visita.`)}`;
  const region = property.address?.match(/Capão da Canoa|Xangri-Lá|Maquiné|Parobé|Osório|Tramandaí|Torres|Carlos Barbosa|Porto Belo/i)?.[0];
  const bedrooms = `${property.title} ${(property.details || []).join(" ")} ${property.notes || ""}`.match(/(\d+)\s*dorm/i)?.[1];
  const area = `${property.title} ${(property.details || []).join(" ")} ${property.notes || ""}`.match(/([\d.,]+)\s*m²/i)?.[1];

  return <main className="min-h-screen bg-[#fbfaf8] text-[#102c3d]">
    <section className="relative min-h-[58vh] overflow-hidden bg-slate-200 sm:min-h-[68vh]">{currentPhoto && <img src={currentPhoto} alt={`Foto principal de ${property.title}`} className="h-full min-h-[58vh] w-full object-cover sm:min-h-[68vh]" />}<div className="absolute inset-0 bg-gradient-to-t from-[#071a26]/85 via-transparent to-[#071a26]/15" /><div className="absolute left-0 right-0 top-0 mx-auto max-w-6xl p-5 sm:p-8"><span className="inline-flex rounded-full bg-[#102c3d]/75 px-3 py-2 text-[10px] font-bold uppercase tracking-[0.18em] text-white backdrop-blur"><span className="mr-2 text-[#d7b874]">●</span> {organization?.name || "Página exclusiva"}</span></div><div className="absolute bottom-0 left-0 right-0 mx-auto max-w-6xl px-5 pb-7 text-white sm:px-8 sm:pb-10"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#d7b874]">Oportunidade selecionada</p><h1 className="mt-2 max-w-4xl text-4xl font-semibold leading-[1.03] tracking-[-0.04em] sm:text-6xl">{property.title}</h1><p className="mt-3 flex max-w-3xl items-start gap-2 text-sm text-white/80 sm:text-base"><MapPin className="mt-0.5 h-4 w-4 shrink-0" />{property.address || "Endereço sob consulta"}</p><p className="mt-5 text-2xl font-extrabold tracking-tight sm:text-4xl">{property.price || "Valor sob consulta"}</p></div></section>
    <div className="relative z-10 mx-auto -mt-5 max-w-6xl px-3 pb-10 sm:px-6"><section className="grid gap-3 rounded-3xl bg-white p-5 shadow-xl sm:grid-cols-[1fr_auto] sm:items-center sm:p-7"><div><div className="flex items-center justify-between gap-3"><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#c7a15a]">Detalhes do imóvel</p><span className="rounded-full bg-[#f6f1e7] px-2.5 py-1 text-[10px] font-bold tracking-[0.12em] text-[#8a6b32]">{property.code}</span></div><h2 className="mt-1 text-lg font-semibold sm:text-xl">{property.title}</h2><p className="mt-1 text-sm text-slate-500">{property.address || "Endereço sob consulta"}</p></div><p className="text-2xl font-extrabold text-[#102c3d]">{property.price || "Valor sob consulta"}</p></section>
      {photos.length > 0 && <section className="rounded-3xl bg-white p-4 shadow-sm sm:p-5"><div className="mb-3 flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[0.17em] text-[#c7a15a]">Galeria do imóvel</p><span className="text-xs text-slate-500">{photoIndex + 1} / {photos.length} fotos</span></div><div className="flex gap-2 overflow-x-auto">{photos.map((photo, index) => <button key={photo} type="button" onClick={() => { setPhotoIndex(index); setLightbox(true); }} className={`h-16 w-24 shrink-0 overflow-hidden rounded-xl border-2 transition ${index === photoIndex ? "border-[#102c3d] ring-2 ring-[#d7b874]" : "border-transparent opacity-70 hover:opacity-100"}`}><img src={photo} alt={`Foto ${index + 1} de ${property.title}`} className="h-full w-full object-cover" /></button>)}</div></section>}
      <div className="mt-3 grid gap-4 lg:grid-cols-[1.25fr_.75fr]"><div className="space-y-4">{(bedrooms || area || region) && <section className="rounded-3xl bg-white p-5 shadow-sm sm:p-7"><h2 className="mb-5 border-l-4 border-[#c7a15a] pl-3 text-lg font-semibold">Visão geral</h2><div className="grid grid-cols-3 gap-2">{bedrooms && <Fact value={bedrooms} label="Dormitórios" icon="⌂" />}{area && <Fact value={`${area} m²`} label="Área privativa" icon="▣" />}{region && <Fact value={region} label="Localização" icon="⌖" />}</div></section>}{property.notes && <section className="rounded-3xl bg-white p-5 shadow-sm sm:p-7"><h2 className="mb-4 border-l-4 border-[#c7a15a] pl-3 text-lg font-semibold">Sobre o imóvel</h2><p className="whitespace-pre-line text-sm leading-7 text-slate-600">{property.notes}</p></section>}{property.details.length > 0 && <section className="rounded-3xl bg-white p-5 shadow-sm sm:p-7"><h2 className="mb-5 border-l-4 border-[#c7a15a] pl-3 text-lg font-semibold">Características</h2><div className="flex flex-wrap gap-2">{property.details.map(detail => <span key={detail} className="rounded-full border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-600">{detail}</span>)}</div></section>}</div><aside className="rounded-3xl bg-white p-5 shadow-sm sm:p-7"><h2 className="mb-5 border-l-4 border-[#c7a15a] pl-3 text-lg font-semibold">Atendimento personalizado</h2><div className="flex items-center gap-4"><div className="grid h-16 w-16 shrink-0 place-items-center overflow-hidden rounded-full border-4 border-[#c7a15a] bg-[#102c3d] text-lg font-extrabold text-white">{broker.photoUrl ? <img src={broker.photoUrl} alt={`Foto de ${broker.name}`} className="h-full w-full object-cover" /> : broker.name.split(/\s+/).slice(0, 2).map(part => part[0]).join("").toUpperCase()}</div><div><p className="font-bold">{broker.name}</p><p className="mt-1 text-xs text-slate-500">Consultoria particular e exclusiva</p><p className="mt-1 text-xs text-slate-500">Atendimento direto pelo WhatsApp</p></div></div><div className="mt-5 border-t pt-4 text-xs leading-relaxed text-slate-500"><ShieldCheck className="mr-1 inline h-4 w-4 text-[#c7a15a]" /><strong className="text-slate-700">Converse diretamente com seu consultor.</strong><br />Informações e disponibilidade sob confirmação.</div></aside></div>
      <div className="sticky bottom-3 z-20 mt-5"><a href={whatsapp} target="_blank" rel="noreferrer" className="flex min-h-14 items-center justify-center gap-2 rounded-2xl bg-[#20bd63] px-5 text-sm font-extrabold text-white shadow-xl transition hover:bg-[#12934a]"><MessageCircle className="h-5 w-5" /> Falar pelo WhatsApp</a></div><footer className="py-5 text-center text-[11px] text-slate-400">Valores e disponibilidade sujeitos a confirmação.</footer></div>
    {lightbox && currentPhoto && <div className="fixed inset-0 z-50 grid place-items-center bg-[#06141d]/95 p-5" role="dialog" aria-modal="true"><button type="button" onClick={() => setLightbox(false)} className="absolute right-5 top-5 rounded-full border border-white/20 bg-white/10 p-2 text-white"><X className="h-5 w-5" /></button><img src={currentPhoto} alt={`Foto ${photoIndex + 1}`} className="max-h-[78vh] max-w-[94vw] rounded-2xl object-contain" />{photos.length > 1 && <div className="absolute bottom-7 flex gap-3"><button type="button" onClick={() => setPhotoIndex((photoIndex - 1 + photos.length) % photos.length)} className="rounded-xl bg-white/10 p-3 text-white"><ChevronLeft /></button><button type="button" onClick={() => setPhotoIndex((photoIndex + 1) % photos.length)} className="rounded-xl bg-white/10 p-3 text-white"><ChevronRight /></button></div>}</div>}
  </main>;
}

function Fact({ value, label, icon }: { value: string; label: string; icon: string }) { return <div className="rounded-2xl border border-slate-200 bg-[#fdfcfb] p-3 text-center"><span className="block text-lg text-[#c7a15a]">{icon}</span><strong className="block text-sm">{value}</strong><span className="block text-[10px] text-slate-500">{label}</span></div>; }
function EmptyState({ title, text }: { title: string; text: string }) { return <main className="grid min-h-screen place-items-center bg-[#fbfaf8] p-6"><div className="w-full max-w-md rounded-3xl bg-white p-10 text-center shadow-xl"><ArrowLeft className="mx-auto mb-5 h-8 w-8 text-[#c7a15a]" /><h1 className="text-xl font-semibold text-[#102c3d]">{title}</h1><p className="mt-2 text-sm text-slate-500">{text}</p></div></main>; }
